### ISSUE TITLE
What server I should to use?

### ISSUE THREAD

**Issue by bubnenkoff** [featurehub-io/featurehub-flutter-sdk#21]
Could you provide example of any server for sse?

It would be perfect if you will show how to integrate it with alfred https://github.com/rknell/alfred

**Comment by rvowles** [comment]
Do you mean using FeatureHub for SSE on a web server?

**Comment by bubnenkoff** [comment]
No I would like to get work SSE on my own. I am using https://github.com/rknell/alfred

**Comment by rvowles** [comment]
Sorry to say that we are focused entirely on SSE's usage inside FeatureHub, this isn't a general purpose library.
