### ISSUE TITLE
_retry continues to be invoked event after _lastStreamDisconnected when _closeOnLastListener is true

### ISSUE THREAD

**Issue by masterwok** [featurehub-io/featurehub-flutter-sdk#24]
I'm using version `1.3.2` of this library and when viewing the console I noticed the following continues to be logged even after the last stream subscriber has disconnected:

```
I/flutter (13111): setting ready state EventSourceReadyState.CONNECTING
```

It doesn't look like an actual request is being made when using Proxyman to investigate requests. However, I don't think `_retry` should continuously be invoked after the last subscriber has disconnected when `closeOnLastStreamClosing` is set to `true`. If exponential backoff is being used and the duration continues to grow on each retry, then it could potentially cause issues later down the line.

Below is a screenshot of `_retry` being invoked when `closeOnLastListener` was set to `true` and the last subscriber has disconnected.

<img width="1113" alt="Screenshot 2023-11-17 at 11 51 30 AM" src="https://github.com/featurehub-io/featurehub-flutter-sdk/assets/5054978/6ed033b7-8629-4ed4-835b-a2d595c7792a">

**Comment by masterwok** [comment]
Issue seemed to be caused by calling `_eventSource?.client.close()` directly.

**Comment by rvowles** [comment]
I think I updated this quite a lot in my new SDK branch.
